AppDirect/slate

- slate-base.Dockerfile
[API-99](https://appdirect.jira.com/browse/API-99)
List additional Jira tickets or Github PRs
Description of the PR. Make language appropriate for other engineers not involved. Should answer:
1. Action. What does it do?
1. Scope. What marketplaces does it affect?
1. Why. Motivation behind PR.
Include as many screenshots as you feel is appropriate to showcase changes.
Be sure to  include team(s) that need to be notified of this update
> API-99: Fix typo in script

- slate-extract.sh
- source/slate-extract.Dockerfile
[API-99](https://appdirect.jira.com/browse/API-99)
List additional Jira tickets or Github PRs
Description of the PR. Make language appropriate for other engineers not involved. Should answer:
1. Action. What does it do?
1. Scope. What marketplaces does it affect?
1. Why. Motivation behind PR.
Include as many screenshots as you feel is appropriate to showcase changes.
Be sure to  include team(s) that need to be notified of this update
> API-99: Add extract script

- source/index.html.md
[API-107](https://appdirect.jira.com/browse/API-107)
List additional Jira tickets or Github PRs
Description of the PR. Make language appropriate for other engineers not involved. Should answer:
1. Action. What does it do?
1. Scope. What marketplaces does it affect?
1. Why. Motivation behind PR.
Include as many screenshots as you feel is appropriate to showcase changes.
Be sure to  include team(s) that need to be notified of this update
> API-107: span must be outside code block

- source/index.html.md
- source/layouts/layout.erb
Jira Link: https://appdirect.jira.com/browse/TD-565
> TD-565: Added Fav Icon

- source/javascripts/all_nosearch.js
- source/javascripts/app/_toc.js
- source/layouts/layout.erb
Jira Link: https://appdirect.jira.com/browse/TD-584
> TD-584: Fixed Page Scroll Issue

- source/javascripts/app/_toc.js
Jira Link : https://appdirect.jira.com/browse/TD-636
> Resolved API reference nav scrolls to the wrong location in the body

- source/layouts/layout.erb
Jira Link : https://appdirect.jira.com/browse/TD-639
> link added for upper left AD logo

- source/javascripts/app/_toc.js
Jira Link: https://appdirect.jira.com/browse/TD-640
> Make Left Nav Jump to a Link instead of Scroll

- source/javascripts/all_nosearch.js
- source/javascripts/app/_toc.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
@jlepage-appdirect kindly have a look into it.
Thanks!
> addition_of_secondary_nav_of_appmarket_and_appbilling

- source/javascripts/app/_toc.js
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-664
> Resolved Page loading Issue

- source/javascripts/all_nosearch.js
- source/javascripts/app/_toc.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-669
> Nav, Logo and Links Issue fixed

- source/layouts/layout.erb
Jira Link : https://appdirect.jira.com/browse/TD-696
@jlepage-appdirect kindly have a look into it.
Thanks!
> TD-696-modifications-of-title

- source/javascripts/all_nosearch.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
@jlepage-appdirect kindly create a zip for it.
Thanks!
> some-header-issue-in-mobile-view

- source/layouts/layout.erb
- source/searchPage.html
Jira Link: https://appdirect.jira.com/browse/TD-830
> Adding Heap Tracking Script

- source/layouts/layout.erb
- source/searchPage.html
Jira Link :https://appdirect.jira.com/browse/TD-826
> Adding Walkme Snippets

- .dockerignore
- Dockerfile
- Jenkinsfile
- build.sh
- launch-slate.sh
- slate-extract.sh
- source/slate-extract.Dockerfile
- source/slate-source.Dockerfile
https://appdirect.jira.com/browse/API-167
Change to create real docker image to use in doc generation.
Add jenkins pipeline to release docker image
Remove slate-extract ad slate-launch docker image. We just have 1 docker image and we need to specify the goal (server or build) to start correctly.
> API-167 : Change to create real docker image to use in doc generation.

- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-836
@jlepage-appdirect kindly have a look into it.
Thanks!
> TD-836-NEW-MODIFICATION

- launch-slate.sh
- source/javascripts/search.js
Jira Link : https://appdirect.jira.com/browse/TD-848
> Updating Search Script

- source/javascripts/header.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-849
> TD-849-NEW

- source/layouts/layout.erb
- source/searchPage.html.erb
- source/stylesheets/screen.css.scss
@adrienzieba kindly merge this. Thanks!
> responsive-changes

- source/javascripts/header.js
- source/stylesheets/screen.css.scss
@adrienzieba kindly have a look into it.
Thanks!
> Sharethis-button-for-mobile and code refactoring for speed up

- source/javascripts/header.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-859
@adrienzieba kindly have a look into it.
Thanks!
> TD-859-NEW-CHANGES

- source/javascripts/search.js
- source/searchPage.html.erb
- source/stylesheets/screen.css.scss
Jira Link: https://appdirect.jira.com/browse/TD-874
> Updating Search Page UI

- source/javascripts/redirect.js
- source/javascripts/search.js
- source/stylesheets/screen.css.scss
@adrienzieba kindly have a look into it.
Thanks!
> search-header-issue

- source/javascripts/search.js
- source/stylesheets/screen.css.scss
Jira Link : https://appdirect.jira.com/browse/TD-902
>  Displaying message on No result Found while Filtering

- source/stylesheets/screen.css.scss
@adrienzieba kindly merge it.
Thanks!
> adding-space-between-filters

- source/javascripts/search.js
- source/searchPage.html.erb
- source/stylesheets/screen.css.scss
Jira Link: https://appdirect.jira.com/browse/TD-903
> Adding Clear All Filters Toggle

- source/javascripts/app/_toc.js
- source/stylesheets/screen.css.scss
Jira Link: https://appdirect.jira.com/browse/TD-920
> Left Nav Search Drop Down List

- Jenkinsfile
https://appdirect.jira.com/browse/API-212
> API-212 : trigger build of api-documentation at the end of the build.

- source/layouts/layout.erb
- source/searchPage.html.erb
Jira Link: https://appdirect.jira.com/browse/TD-948
> Make Doc Search Read Only

- source/layouts/layout.erb
- source/searchPage.html.erb
> Revert "Make Doc Search Read Only"

- source/javascripts/search.js
Jira Link : https://appdirect.jira.com/browse/TD-1129
> TD-1129:Appwise-Search-Title-Modification

- source/layouts/layout.erb
[TD-1501](https://appdirect.jira.com/browse/TD-1501)
> Adding Heap, Walkme, Google Analytics Script

- source/javascripts/app/_toc.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
[TD-1527](https://appdirect.jira.com/browse/TD-1527)
##___SCREENSHOTS__##
> Adding Header, SubNav and Adjusting Styling for API Reports V1

- source/javascripts/app/_toc.js
- source/javascripts/lib/_jquery.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
[TD-1528](https://appdirect.jira.com/browse/TD-1528)
##__SCREENSHOTS__##
> Adding Header, SubNav and Adjusting Styling for API Reports V2

- source/javascripts/app/_toc.js
- source/javascripts/jquery.js
- source/javascripts/lib/_jquery.js
- source/javascripts/redirect.js
- source/layouts/layout.erb
- source/searchPage.html.erb
- source/stylesheets/screen.css.scss
[TD-1529](https://appdirect.jira.com/browse/TD-1529)
##__SCREENSHOTS__##
> Adding Header, SubNav and Adjusting Styling for API Storefront

- source/index.html.md
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
[TD-1499](https://appdirect.jira.com/browse/TD-1499)
> Changed the text to API Help and made it a link.
> 
> Changed the page title to API Help from API Reference.
> 
> Did the above for all the pages.
> 
> Let me know if you want any changes.
> Changing Sub-Nav text to API Help and making it link, changing page title for all pages.
